services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./.psql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=laklak
      - POSTGRES_USER=laklak
      - POSTGRES_DB=laklak
  jaeger:
    image: jaegertracing/all-in-one:${JAEGER_VERSION:-latest}
    ports:
      - 16686:16686
    environment:
      - LOG_LEVEL=debug
  otel-collector:
    image: otel/opentelemetry-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
#  hotrod:
#    image: jaegertracing/example-hotrod:${JAEGER_VERSION:-latest}
#    # To run the latest trunk build, find the tag at Docker Hub and use the line below
#    # https://hub.docker.com/r/jaegertracing/example-hotrod-snapshot/tags
#    #image: jaegertracing/example-hotrod-snapshot:0ab8f2fcb12ff0d10830c1ee3bb52b745522db6c
#    ports:
#      - "8080:8080"
#      - "8083:8083"
#    command: [ "all" ]
#    environment:
#      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
#    depends_on:
#      - jaeger
