services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./.psql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=laklak
      - POSTGRES_USER=laklak
      - POSTGRES_DB=laklak
  jaeger:
    image: jaegertracing/all-in-one:${JAEGER_VERSION:-latest}
    ports:
      - 16686:16686
    environment:
      - LOG_LEVEL=debug
  otel-collector:
    image: otel/opentelemetry-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./infrastructures/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  loki:
    image: grafana/loki:2.9.2
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/loki.yaml
    volumes:
      - ./infrastructures/loki.yaml:/etc/loki/loki.yaml
  grafana:
    image: grafana/grafana:9.1.6
    ports:
      - 3000:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    volumes:
      - ./infrastructures/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - ./infrastructures/promtail.yaml:/etc/promtail/promtail.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9080:9080
    command: -config.file=/etc/promtail/promtail.yaml -config.expand-env=true
