services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./.psql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=laklak
      - POSTGRES_USER=laklak
      - POSTGRES_DB=laklak